<main>
    <h2>Edit Book</h2>

    <form action="./editBook.php" method="POST" >

        <p>
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="<?= $book['title'] ?>"/>
        </p>
        
        <p>
            <label for="tome_number">Tome number</label>
            <input type="text" name="tome_number" id="tome_number">
        </p>

        <p>
            <label for="description">Description</label>
            <textarea name="description" id="description"><?= $book['description'] ?></textarea>
        </p>

        <p>
            <label for="author">Author</label>
            <input type="text" name="author" id="author" value="<?= $book['author'] ?>"/>
        </p>

        <p>
            <label for="publish_at">Publish at</label>
            <input type="text" name="publish_at" id="publish_at" value="<?= $book['publish_at'] ?>"/>
        </p>

        <p>
            <label for="serie_name">Serie name</label>
            <input type="text" name="serie_name" id="serie_name" value="<?= $book['serie_name'] ?>"/>
        </p>

        <p>
            <label for="cover">Cover</label>
            <input type="text" name="cover" id="cover" value="<?= $book['cover'] ?>"/>
        </p>

        <p>
            <label for="edition">Edition</label>
            <input type="text" name="edition" id="edition" value="<?= $book['edition'] ?>"/>
        </p>
        
        <input type="hidden" name="id" value="<?= $book['id'] ?>">

        <button type="submit">Update</button>
    </form>
</main>