<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/style/app.css">
    <title>Library</title>
</head>
    <body class="grid">

    <?php include_once './templates/parts/header.phtml'; ?>
    
    <?php include_once './templates/' . $templateName; ?>
    
    <?php include_once './templates/parts/footer.phtml'; ?>
    
</body>
</html>