<main>

    <h2>New Book</h2>

    <form action="./addBook.php" method="POST">

        <p>
            <label for="title">Title</label>
            <input type="text" name="title" id="title">
        </p>
        
        <p>
            <label for="tome_number">Tome number</label>
            <input type="text" name="tome_number" id="tome_number">
        </p>

        <p>
            <label for="description">Description</label>
            <textarea name="description" id="description"></textarea>
        </p>

        <p>
            <label for="author">Author</label>
            <input type="text" name="author" id="author">
        </p>

        <p>
            <label for="publish_at">Publish at</label>
            <input type="year" name="publish_at" id="publish_at">
        </p>

        <p>
            <label for="serie_name">Serie name</label>
            <input type="text" name="serie_name" id="serie_name">
        </p>

        <p>
            <label for="cover">Cover</label>
            <input type="text" name="cover" id="cover">
        </p>

        <p>
            <label for="edition">Edition</label>
            <input type="text" name="edition" id="edition">
        </p>

        <button type="submit">Add Book</button>

    </form>

</main>