<main>

    <h1>Register</h1>

        <form action="./addUser.php" method="POST" enctype="multipart/form-data">

            <p>
                <label for="username">Username</label>
                <input type="text" id="username" name="username">
            </p>

            <p>
                <label for="email">E-mail</label>
                <input type="email" id="email" name="email">
            </p>
            
            <p>
                <label for="password">Password</label>
                <input type="password" id="password" name="password">
            </p>
            
            <p>
                <label for="avatar">Avatar</label>
                <input type="file" id="avatar" name="avatar">
            </p>

            <button type="submit">register me</button>

        </form>
</main>