<main>
    <section class="block-book" >
        <h2 class="book-title" >Tome <?= $book['tome_number'] ?> : <?= $book['title'] ?></h2>
        <article class="cover-description" >
            <img class="clearfix" src="<?= $book['cover'] ?>" alt="Cover of book">
            <p class="book-description">
                <?= $book['description'] ?>
            </p>
        </article>
        <article class="info-content">
            <p class="infos">
                <span>Serie : <a href=""> <?= $book['serie_name'] ?> </a></span>
                <span>Author : <a href=""><?= $book['author'] ?> </a></span>
                <span>Publish at : <?= $book['publish_at'] ?></span>
                <span>Edition : <a href=""><?= $book['edition'] ?> </a></span>
            </p>
            <div class="button-content">
                <a class="button" href="./updateBook.php?id=<?= $book['id'] ?>">EDIT</a>
                <a class="button" href="./deleteBook.php?id=<?= $book['id'] ?>">DELETE</a>
            </div>
        </article>
    </section>

</main>