<main>

    <h1>sign In</h1>

    <form action="./authUser.php" method="POST">
        <p class="my-2">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" />
        </p>
        <p class="my-2">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" />
        </p>
        <button type="submit">Sign me in</button>
    </form>

</main>