<header>
    <h1 class="logo">Library</h1>
    <input class="menu-btn" type="checkbox" id="menu-btn" />
    <label class="menu-icon" for="menu-btn"><span class="nav-icon"></span></label>
    <nav class="menu">
        <p><a href="./index.php">Home</a></p>
        <p><a href="./index.php">Authors</a></p>
        <p><a href="./index.php">Editions</a></p>
        <p><a href="./newBook.php">New Book</a></p>
        <p><a href="./index.php">About</a></p>
        <p><a href="./index.php">Contact</a></p>
        <p><a href="./register.php">Register</a></p>
        <p><a href="./signIn.php">Sign In</a></p>
        <p><a href="./signOut.php">Sign Out</a></p>
    </nav>
</header>